const soal = [
  { q: "What is the opposite of 'hot'?", options: ["Cold", "Warm", "Cool", "Boiling"], answer: "Cold" },
  { q: "Choose the correct sentence:", options: ["He go to school every day.", "He goes to school every day.", "He going to school.", "He gone to school."], answer: "He goes to school every day." },
  { q: "What does 'hungry' mean?", options: ["Feeling sleepy", "Feeling tired", "Feeling thirsty", "Feeling need to eat"], answer: "Feeling need to eat" },
  { q: "She ___ a student.", options: ["am", "is", "are", "be"], answer: "is" },
  { q: "Which one is an animal?", options: ["Table", "Chair", "Cat", "Book"], answer: "Cat" },
  { q: "What color is the sky on a clear day?", options: ["Blue", "Red", "Green", "Yellow"], answer: "Blue" },
  { q: "Choose the correct word: 'I ___ soccer every weekend.'", options: ["play", "plays", "playing", "played"], answer: "play" },
  { q: "The plural of 'child' is ___", options: ["childs", "children", "childes", "child"], answer: "children" },
  { q: "Which one means 'happy'?", options: ["Sad", "Glad", "Angry", "Tired"], answer: "Glad" },
  { q: "What time do you go to school?", options: ["At seven o'clock", "In my bag", "Very fast", "With my friend"], answer: "At seven o'clock" },
  { q: "Choose the correct question: ___ you like ice cream?", options: ["Do", "Does", "Did", "Doing"], answer: "Do" },
  { q: "What is the opposite of 'fast'?", options: ["Quick", "Slow", "Speed", "Move"], answer: "Slow" },
  { q: "Which one is a fruit?", options: ["Carrot", "Potato", "Apple", "Cabbage"], answer: "Apple" },
  { q: "They ___ in the park now.", options: ["play", "playing", "are playing", "plays"], answer: "are playing" },
  { q: "Choose the correct spelling:", options: ["Beutiful", "Beautiful", "Beautifull", "Beatiful"], answer: "Beautiful" },
  { q: "What is the past form of 'go'?", options: ["Goed", "Went", "Gone", "Going"], answer: "Went" },
  { q: "He ___ a new bicycle last week.", options: ["buys", "buy", "bought", "buying"], answer: "bought" },
  { q: "Which one is used to write?", options: ["Pen", "Spoon", "Plate", "Bottle"], answer: "Pen" },
  { q: "My father is a ___. He teaches students.", options: ["Doctor", "Teacher", "Farmer", "Driver"], answer: "Teacher" },
  { q: "We use our eyes to ___", options: ["see", "hear", "smell", "touch"], answer: "see" },
  { q: "Choose the correct sentence:", options: ["She don't like cats.", "She doesn't like cats.", "She not like cats.", "She no like cats."], answer: "She doesn't like cats." },
  { q: "The opposite of 'big' is ___", options: ["Large", "Small", "Huge", "Wide"], answer: "Small" },
  { q: "What do you call a baby cat?", options: ["Puppy", "Kitten", "Cub", "Chick"], answer: "Kitten" },
  { q: "What does 'library' mean?", options: ["A place to read books", "A place to eat", "A place to sleep", "A place to shop"], answer: "A place to read books" },
  { q: "I have two ___: one brother and one sister.", options: ["child", "friends", "siblings", "parents"], answer: "siblings" },
  { q: "She ___ breakfast every morning.", options: ["eat", "eats", "ate", "eating"], answer: "eats" },
  { q: "Which is a day of the week?", options: ["June", "Monday", "Winter", "Morning"], answer: "Monday" },
  { q: "My favorite subject is ___", options: ["reading", "math", "running", "play"], answer: "math" },
  { q: "I usually brush my ___ before sleeping.", options: ["hair", "face", "teeth", "hands"], answer: "teeth" },
  { q: "How many legs does a spider have?", options: ["Six", "Eight", "Ten", "Four"], answer: "Eight" },
  { q: "Which one is correct?", options: ["He can sings.", "He can sing.", "He singing.", "He sings can."], answer: "He can sing." },
  { q: "What is the opposite of 'early'?", options: ["Soon", "Late", "Fast", "Quick"], answer: "Late" },
  { q: "She is ___ than her sister.", options: ["taller", "tallest", "more tall", "most tall"], answer: "taller" },
  { q: "Which word means 'delicious'?", options: ["Bad", "Tasty", "Ugly", "Dry"], answer: "Tasty" },
  { q: "We drink water when we are ___", options: ["tired", "hungry", "thirsty", "sleepy"], answer: "thirsty" },
  { q: "The plural of 'mouse' is ___", options: ["mouses", "mice", "mouse", "mices"], answer: "mice" },
  { q: "Choose the correct word: 'There ___ some apples on the table.'", options: ["is", "are", "was", "be"], answer: "are" },
  { q: "What time is it when the clock shows 12:00?", options: ["Midnight", "Noon", "Morning", "Evening"], answer: "Noon" },
  { q: "Which one is a bird?", options: ["Fish", "Eagle", "Cat", "Dog"], answer: "Eagle" },
  { q: "I can’t see at night without a ___", options: ["book", "lamp", "shoe", "door"], answer: "lamp" },
  { q: "Which one is an adjective?", options: ["Run", "Blue", "Quickly", "Jump"], answer: "Blue" },
  { q: "The opposite of 'beautiful' is ___", options: ["Pretty", "Ugly", "Cute", "Lovely"], answer: "Ugly" },
  { q: "Choose the correct sentence:", options: ["They was happy.", "They were happy.", "They be happy.", "They are was happy."], answer: "They were happy." },
  { q: "I ___ to music every day.", options: ["listen", "listens", "listened", "listening"], answer: "listen" },
  { q: "Where do students study?", options: ["School", "Market", "Hospital", "Garden"], answer: "School" },
  { q: "Choose the correct word: 'She has a ___ dress.'", options: ["red beautiful", "beautiful red", "beauty red", "redly beautiful"], answer: "beautiful red" },
  { q: "What do we wear on our feet?", options: ["Hat", "Gloves", "Shoes", "Shirt"], answer: "Shoes" },
  { q: "How many months are there in a year?", options: ["10", "11", "12", "13"], answer: "12" },
  { q: "Which one means 'angry'?", options: ["Happy", "Mad", "Excited", "Calm"], answer: "Mad" },
  { q: "Choose the correct form: 'She ___ reading a book now.'", options: ["is", "are", "am", "be"], answer: "is" },
  { q: "My mom cooks in the ___", options: ["bedroom", "kitchen", "garage", "bathroom"], answer: "kitchen" },
  { q: "We sleep at ___", options: ["day", "night", "morning", "noon"], answer: "night" },
  { q: "I usually go to school ______ 7 a.m.", options: ["on", "at", "in", "by"], answer: "at" },
  {q: "He _______ TV every night.", options: ["watch", "watching", "watches", "watched"], answer: "watches"},
  {q: "My sister can play the ______.", options: ["guitar", "sing", "dance", "game"], answer: "guitar"},
  {q: "How many days are there in a week?", options: ["5", "6", "7", "8"], answer: "7"},
  {q: "What color is the sky on a clear day?", options: ["blue", "green", "black", "red"], answer: "blue"},
  {q: "She ______ her homework now.", options: ["does", "doing", "did", "is doing"], answer: "is doing"},
  {q: "Where ______ you yesterday?", options: ["was", "were", "are", "is"], answer: "were"},
  {q: "I don't like coffee. I prefer ______.", options: ["tea", "milk", "juice", "water"], answer: "tea"},
  {q: "The opposite of 'tall' is ______.", options: ["short", "long", "big", "thin"], answer: "short"},
  {q: "My father works in a hospital. He is a ______.", options: ["teacher", "doctor", "driver", "chef"], answer: "doctor"},
  {q: "There ______ a lot of people at the concert.", options: ["was", "were", "is", "be"], answer: "were"},
  {q: "I like reading books ______ the library.", options: ["on", "in", "at", "by"], answer: "in"},
  {q: "She is ______ than her sister.", options: ["beautiful", "more beautiful", "most beautiful", "beautifuller"], answer: "more beautiful"},
  {q: "Don't forget to ______ your homework!", options: ["do", "make", "play", "take"], answer: "do"},
  {q: "We ______ in Bandung last weekend.", options: ["go", "goes", "went", "going"], answer: "went"},
  {q: "He can swim, ______ he?", options: ["can", "can't", "does", "is"], answer: "can't"},
  {q: "I have two ______: a cat and a rabbit.", options: ["pets", "pet", "animal", "dog"], answer: "pets"},
  {q: "Let's ______ football this afternoon!", options: ["play", "go", "do", "watch"], answer: "play"},
  {q: "The sun rises in the ______.", options: ["north", "east", "west", "south"], answer: "east"},
  {q: "She never ______ to school late.", options: ["come", "comes", "came", "coming"], answer: "comes"},
  {q: "Do you like ice cream? ______, I love it!", options: ["No", "Yes", "Not really", "Never"], answer: "Yes"},
  {q: "My bag is ______ than yours.", options: ["heavy", "heavier", "heaviest", "more heavy"], answer: "heavier"},
  {q: "We often ______ English songs.", options: ["listen to", "hear", "read", "watch"], answer: "listen to"},
  {q: "______ you ever been to Bali?", options: ["Did", "Have", "Are", "Do"], answer: "Have"},
  {q: "My favorite subject is ______.", options: ["soccer", "English", "movie", "sleep"], answer: "English"},
  {q: "He is ______ lunch right now.", options: ["eat", "eating", "ate", "eats"], answer: "eating"},
  {q: "I was born ______ 2010.", options: ["at", "on", "in", "by"], answer: "in"},
  {q: "There is some milk in the ______.", options: ["bottle", "plate", "bag", "glass"], answer: "bottle"},
  {q: "What time is it? It's ______ o'clock.", options: ["ten", "in", "a", "for"], answer: "ten"},
  {q: "We ______ watch movies together.", options: ["usually", "never", "rarely", "once"], answer: "usually"},
  {q: "This book is ______ than that one.", options: ["good", "better", "best", "more good"], answer: "better"},
  {q: "I saw a beautiful ______ in the garden.", options: ["flower", "table", "chair", "pen"], answer: "flower"},
  {q: "He drives too fast. He should be more ______.", options: ["careful", "careless", "fast", "quick"], answer: "careful"},
  {q: "She didn't come to school ______ she was sick.", options: ["because", "so", "but", "and"], answer: "because"},
  {q: "What ______ you doing?", options: ["is", "are", "were", "do"], answer: "are"},
  {q: "I have ______ homework to do tonight.", options: ["many", "a lot of", "much", "few"], answer: "a lot of"},
  {q: "Please open the window, it's very ______.", options: ["hot", "cold", "windy", "dark"], answer: "hot"},
  {q: "There are twelve ______ in a year.", options: ["days", "weeks", "months", "hours"], answer: "months"},
  {q: "We went to the beach and built a ______.", options: ["castle", "sandcastle", "house", "tower"], answer: "sandcastle"},
  {q: "My favorite food is ______.", options: ["pizza", "run", "read", "write"], answer: "pizza"},
  {q: "Can you ______ English songs?", options: ["sing", "dance", "read", "cook"], answer: "sing"},
  {q: "The plural of 'child' is ______.", options: ["childs", "children", "childes", "childrens"], answer: "children"},
  {q: "My brother ______ basketball every weekend.", options: ["play", "plays", "playing", "played"], answer: "plays"},
  {q: "The cat is ______ the table.", options: ["on", "under", "behind", "in front of"], answer: "under"},
  {q: "How ______ sugar do you want?", options: ["many", "much", "few", "some"], answer: "much"},
  {q: "Let's go ______ by bike.", options: ["there", "here", "home", "school"], answer: "home"},
  {q: "I like to draw and paint. It's my ______.", options: ["hobby", "work", "subject", "lesson"], answer: "hobby"},
  {q: "My grandparents live in the ______.", options: ["village", "city", "market", "store"], answer: "village"},
  {q: "He _______ his bike to school.", options: ["rides", "drives", "flies", "goes"], answer: "rides"},
  {q: "I can't find my pencil. Can I ______ yours?", options: ["borrow", "lend", "take", "buy"], answer: "borrow"},
  {q: "There _______ any apples left.", options: ["isn't", "aren't", "wasn't", "not"], answer: "aren't"},
];
// Shuffle questions
function shuffle(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}
shuffle(soal);



