const soal = [
  { pertanyaan: "What is the opposite of 'hot'?", pilihan: ["Cold", "Warm", "Cool", "Boiling"], jawaban: "Cold" },
  { pertanyaan: "Choose the correct sentence:", pilihan: ["He go to school every day.", "He goes to school every day.", "He going to school.", "He gone to school."], jawaban: "He goes to school every day." },
  { pertanyaan: "What does 'hungry' mean?", pilihan: ["Feeling sleepy", "Feeling tired", "Feeling thirsty", "Feeling need to eat"], jawaban: "Feeling need to eat" },
  { pertanyaan: "She ___ a student.", pilihan: ["am", "is", "are", "be"], jawaban: "is" },
  { pertanyaan: "Which one is an animal?", pilihan: ["Table", "Chair", "Cat", "Book"], jawaban: "Cat" },
  { pertanyaan: "What color is the sky on a clear day?", pilihan: ["Blue", "Red", "Green", "Yellow"], jawaban: "Blue" },
  { pertanyaan: "Choose the correct word: 'I ___ soccer every weekend.'", pilihan: ["play", "plays", "playing", "played"], jawaban: "play" },
  { pertanyaan: "The plural of 'child' is ___", pilihan: ["childs", "children", "childes", "child"], jawaban: "children" },
  { pertanyaan: "Which one means 'happy'?", pilihan: ["Sad", "Glad", "Angry", "Tired"], jawaban: "Glad" },
  { pertanyaan: "What time do you go to school?", pilihan: ["At seven o'clock", "In my bag", "Very fast", "With my friend"], jawaban: "At seven o'clock" },
  { pertanyaan: "Choose the correct question: ___ you like ice cream?", pilihan: ["Do", "Does", "Did", "Doing"], jawaban: "Do" },
  { pertanyaan: "What is the opposite of 'fast'?", pilihan: ["Quick", "Slow", "Speed", "Move"], jawaban: "Slow" },
  { pertanyaan: "Which one is a fruit?", pilihan: ["Carrot", "Potato", "Apple", "Cabbage"], jawaban: "Apple" },
  { pertanyaan: "They ___ in the park now.", pilihan: ["play", "playing", "are playing", "plays"], jawaban: "are playing" },
  { pertanyaan: "Choose the correct spelling:", pilihan: ["Beutiful", "Beautiful", "Beautifull", "Beatiful"], jawaban: "Beautiful" },
  { pertanyaan: "What is the past form of 'go'?", pilihan: ["Goed", "Went", "Gone", "Going"], jawaban: "Went" },
  { pertanyaan: "He ___ a new bicycle last week.", pilihan: ["buys", "buy", "bought", "buying"], jawaban: "bought" },
  { pertanyaan: "Which one is used to write?", pilihan: ["Pen", "Spoon", "Plate", "Bottle"], jawaban: "Pen" },
  { pertanyaan: "My father is a ___. He teaches students.", pilihan: ["Doctor", "Teacher", "Farmer", "Driver"], jawaban: "Teacher" },
  { pertanyaan: "We use our eyes to ___", pilihan: ["see", "hear", "smell", "touch"], jawaban: "see" },
  { pertanyaan: "Choose the correct sentence:", pilihan: ["She don't like cats.", "She doesn't like cats.", "She not like cats.", "She no like cats."], jawaban: "She doesn't like cats." },
  { pertanyaan: "The opposite of 'big' is ___", pilihan: ["Large", "Small", "Huge", "Wide"], jawaban: "Small" },
  { pertanyaan: "What do you call a baby cat?", pilihan: ["Puppy", "Kitten", "Cub", "Chick"], jawaban: "Kitten" },
  { pertanyaan: "What does 'library' mean?", pilihan: ["A place to read books", "A place to eat", "A place to sleep", "A place to shop"], jawaban: "A place to read books" },
  { pertanyaan: "I have two ___: one brother and one sister.", pilihan: ["child", "friends", "siblings", "parents"], jawaban: "siblings" },
  { pertanyaan: "She ___ breakfast every morning.", pilihan: ["eat", "eats", "ate", "eating"], jawaban: "eats" },
  { pertanyaan: "Which is a day of the week?", pilihan: ["June", "Monday", "Winter", "Morning"], jawaban: "Monday" },
  { pertanyaan: "My favorite subject is ___", pilihan: ["reading", "math", "running", "play"], jawaban: "math" },
  { pertanyaan: "I usually brush my ___ before sleeping.", pilihan: ["hair", "face", "teeth", "hands"], jawaban: "teeth" },
  { pertanyaan: "How many legs does a spider have?", pilihan: ["Six", "Eight", "Ten", "Four"], jawaban: "Eight" },
  { pertanyaan: "Which one is correct?", pilihan: ["He can sings.", "He can sing.", "He singing.", "He sings can."], jawaban: "He can sing." },
  { pertanyaan: "What is the opposite of 'early'?", pilihan: ["Soon", "Late", "Fast", "Quick"], jawaban: "Late" },
  { pertanyaan: "She is ___ than her sister.", pilihan: ["taller", "tallest", "more tall", "most tall"], jawaban: "taller" },
  { pertanyaan: "Which word means 'delicious'?", pilihan: ["Bad", "Tasty", "Ugly", "Dry"], jawaban: "Tasty" },
  { pertanyaan: "We drink water when we are ___", pilihan: ["tired", "hungry", "thirsty", "sleepy"], jawaban: "thirsty" },
  { pertanyaan: "The plural of 'mouse' is ___", pilihan: ["mouses", "mice", "mouse", "mices"], jawaban: "mice" },
  { pertanyaan: "Choose the correct word: 'There ___ some apples on the table.'", pilihan: ["is", "are", "was", "be"], jawaban: "are" },
  { pertanyaan: "What time is it when the clock shows 12:00?", pilihan: ["Midnight", "Noon", "Morning", "Evening"], jawaban: "Noon" },
  { pertanyaan: "Which one is a bird?", pilihan: ["Fish", "Eagle", "Cat", "Dog"], jawaban: "Eagle" },
  { pertanyaan: "I can’t see at night without a ___", pilihan: ["book", "lamp", "shoe", "door"], jawaban: "lamp" },
  { pertanyaan: "Which one is an adjective?", pilihan: ["Run", "Blue", "Quickly", "Jump"], jawaban: "Blue" },
  { pertanyaan: "The opposite of 'beautiful' is ___", pilihan: ["Pretty", "Ugly", "Cute", "Lovely"], jawaban: "Ugly" },
  { pertanyaan: "Choose the correct sentence:", pilihan: ["They was happy.", "They were happy.", "They be happy.", "They are was happy."], jawaban: "They were happy." },
  { pertanyaan: "I ___ to music every day.", pilihan: ["listen", "listens", "listened", "listening"], jawaban: "listen" },
  { pertanyaan: "Where do students study?", pilihan: ["School", "Market", "Hospital", "Garden"], jawaban: "School" },
  { pertanyaan: "Choose the correct word: 'She has a ___ dress.'", pilihan: ["red beautiful", "beautiful red", "beauty red", "redly beautiful"], jawaban: "beautiful red" },
  { pertanyaan: "What do we wear on our feet?", pilihan: ["Hat", "Gloves", "Shoes", "Shirt"], jawaban: "Shoes" },
  { pertanyaan: "How many months are there in a year?", pilihan: ["10", "11", "12", "13"], jawaban: "12" },
  { pertanyaan: "Which one means 'angry'?", pilihan: ["Happy", "Mad", "Excited", "Calm"], jawaban: "Mad" },
  { pertanyaan: "Choose the correct form: 'She ___ reading a book now.'", pilihan: ["is", "are", "am", "be"], jawaban: "is" },
  { pertanyaan: "My mom cooks in the ___", pilihan: ["bedroom", "kitchen", "garage", "bathroom"], jawaban: "kitchen" },
  { pertanyaan: "We sleep at ___", pilihan: ["day", "night", "morning", "noon"], jawaban: "night" }
  {q: "I usually go to school ______ 7 a.m.", options: ["on", "at", "in", "by"], answer: "at"},
  {q: "He _______ TV every night.", options: ["watch", "watching", "watches", "watched"], answer: "watches"},
  {q: "My sister can play the ______.", options: ["guitar", "sing", "dance", "game"], answer: "guitar"},
  {q: "How many days are there in a week?", options: ["5", "6", "7", "8"], answer: "7"},
  {q: "What color is the sky on a clear day?", options: ["blue", "green", "black", "red"], answer: "blue"},
  {q: "She ______ her homework now.", options: ["does", "doing", "did", "is doing"], answer: "is doing"},
  {q: "Where ______ you yesterday?", options: ["was", "were", "are", "is"], answer: "were"},
  {q: "I don't like coffee. I prefer ______.", options: ["tea", "milk", "juice", "water"], answer: "tea"},
  {q: "The opposite of 'tall' is ______.", options: ["short", "long", "big", "thin"], answer: "short"},
  {q: "My father works in a hospital. He is a ______.", options: ["teacher", "doctor", "driver", "chef"], answer: "doctor"},
  {q: "There ______ a lot of people at the concert.", options: ["was", "were", "is", "be"], answer: "were"},
  {q: "I like reading books ______ the library.", options: ["on", "in", "at", "by"], answer: "in"},
  {q: "She is ______ than her sister.", options: ["beautiful", "more beautiful", "most beautiful", "beautifuller"], answer: "more beautiful"},
  {q: "Don't forget to ______ your homework!", options: ["do", "make", "play", "take"], answer: "do"},
  {q: "We ______ in Bandung last weekend.", options: ["go", "goes", "went", "going"], answer: "went"},
  {q: "He can swim, ______ he?", options: ["can", "can't", "does", "is"], answer: "can't"},
  {q: "I have two ______: a cat and a rabbit.", options: ["pets", "pet", "animal", "dog"], answer: "pets"},
  {q: "Let's ______ football this afternoon!", options: ["play", "go", "do", "watch"], answer: "play"},
  {q: "The sun rises in the ______.", options: ["north", "east", "west", "south"], answer: "east"},
  {q: "She never ______ to school late.", options: ["come", "comes", "came", "coming"], answer: "comes"},
  {q: "Do you like ice cream? ______, I love it!", options: ["No", "Yes", "Not really", "Never"], answer: "Yes"},
  {q: "My bag is ______ than yours.", options: ["heavy", "heavier", "heaviest", "more heavy"], answer: "heavier"},
  {q: "We often ______ English songs.", options: ["listen to", "hear", "read", "watch"], answer: "listen to"},
  {q: "______ you ever been to Bali?", options: ["Did", "Have", "Are", "Do"], answer: "Have"},
  {q: "My favorite subject is ______.", options: ["soccer", "English", "movie", "sleep"], answer: "English"},
  {q: "He is ______ lunch right now.", options: ["eat", "eating", "ate", "eats"], answer: "eating"},
  {q: "I was born ______ 2010.", options: ["at", "on", "in", "by"], answer: "in"},
  {q: "There is some milk in the ______.", options: ["bottle", "plate", "bag", "glass"], answer: "bottle"},
  {q: "What time is it? It's ______ o'clock.", options: ["ten", "in", "a", "for"], answer: "ten"},
  {q: "We ______ watch movies together.", options: ["usually", "never", "rarely", "once"], answer: "usually"},
  {q: "This book is ______ than that one.", options: ["good", "better", "best", "more good"], answer: "better"},
  {q: "I saw a beautiful ______ in the garden.", options: ["flower", "table", "chair", "pen"], answer: "flower"},
  {q: "He drives too fast. He should be more ______.", options: ["careful", "careless", "fast", "quick"], answer: "careful"},
  {q: "She didn't come to school ______ she was sick.", options: ["because", "so", "but", "and"], answer: "because"},
  {q: "What ______ you doing?", options: ["is", "are", "were", "do"], answer: "are"},
  {q: "I have ______ homework to do tonight.", options: ["many", "a lot of", "much", "few"], answer: "a lot of"},
  {q: "Please open the window, it's very ______.", options: ["hot", "cold", "windy", "dark"], answer: "hot"},
  {q: "There are twelve ______ in a year.", options: ["days", "weeks", "months", "hours"], answer: "months"},
  {q: "We went to the beach and built a ______.", options: ["castle", "sandcastle", "house", "tower"], answer: "sandcastle"},
  {q: "My favorite food is ______.", options: ["pizza", "run", "read", "write"], answer: "pizza"},
  {q: "Can you ______ English songs?", options: ["sing", "dance", "read", "cook"], answer: "sing"},
  {q: "The plural of 'child' is ______.", options: ["childs", "children", "childes", "childrens"], answer: "children"},
  {q: "My brother ______ basketball every weekend.", options: ["play", "plays", "playing", "played"], answer: "plays"},
  {q: "The cat is ______ the table.", options: ["on", "under", "behind", "in front of"], answer: "under"},
  {q: "How ______ sugar do you want?", options: ["many", "much", "few", "some"], answer: "much"},
  {q: "Let's go ______ by bike.", options: ["there", "here", "home", "school"], answer: "home"},
  {q: "I like to draw and paint. It's my ______.", options: ["hobby", "work", "subject", "lesson"], answer: "hobby"},
  {q: "My grandparents live in the ______.", options: ["village", "city", "market", "store"], answer: "village"},
  {q: "He _______ his bike to school.", options: ["rides", "drives", "flies", "goes"], answer: "rides"},
  {q: "I can't find my pencil. Can I ______ yours?", options: ["borrow", "lend", "take", "buy"], answer: "borrow"},
  {q: "There _______ any apples left.", options: ["isn't", "aren't", "wasn't", "not"], answer: "aren't"},
];
// Shuffle questions
function shuffle(array) {
  for (let i = array.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [array[i], array[j]] = [array[j], array[i]];
  }
}
shuffle(soal);

